[package]
name = "taskrunner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
jsonpath_lib = "0.3"
handlebars = "4.4"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0.98"